let isRunning = false
let evasionDirection = 1
let speed = 200

// Initialize radio for communication
radio.setGroup(1)

// Function to start the robot
function startRobot() {
    isRunning = true
        basic.showIcon(IconNames.Yes)
            basic.pause(1000)
                basic.clearScreen()
                    basic.forever(function () {
                            if (!isRunning) return

                                    let distance = getDistance()
                                            if (distance < 20) {
                                                        // Enemy detected close by
                                                                    displayAngryFace()
                                                                                pushEnemy()
                                                                                        }

                                                                                                if (pins.digitalReadPin(DigitalPin.P1) == 0) {
                                                                                                            // IR sensor detects edge
                                                                                                                        handleEdgeDetection()
                                                                                                                                }

                                                                                                                                        if (pins.digitalReadPin(DigitalPin.P0) == 0) {
                                                                                                                                                    // Line tracker sensor detects edge
                                                                                                                                                                handleEdgeDetection()
                                                                                                                                                                        }
                                                                                                                                                                            })
                                                                                                                                                                            }

                                                                                                                                                                            // Function to stop the robot
                                                                                                                                                                            function stopRobot() {
                                                                                                                                                                                isRunning = false
                                                                                                                                                                                    robotbit.MotorStopAll()
                                                                                                                                                                                        basic.showIcon(IconNames.No)
                                                                                                                                                                                            basic.pause(1000)
                                                                                                                                                                                                basic.clearScreen()
                                                                                                                                                                                                }

                                                                                                                                                                                                // Function to get distance from ultrasonic sensor
                                                                                                                                                                                                function getDistance(): number {
                                                                                                                                                                                                    pins.digitalWritePin(DigitalPin.P14, 0)
                                                                                                                                                                                                        control.waitMicros(2)
                                                                                                                                                                                                            pins.digitalWritePin(DigitalPin.P14, 1)
                                                                                                                                                                                                                control.waitMicros(10)
                                                                                                                                                                                                                    pins.digitalWritePin(DigitalPin.P14, 0)
                                                                                                                                                                                                                        return pins.pulseIn(DigitalPin.P15, PulseValue.High) / 58
                                                                                                                                                                                                                        }

                                                                                                                                                                                                                        // Function to handle edge detection
                                                                                                                                                                                                                        function handleEdgeDetection() {
                                                                                                                                                                                                                            displayHooray()
                                                                                                                                                                                                                                celebrateEnemyOut()
                                                                                                                                                                                                                                    stopRobot()
                                                                                                                                                                                                                                        basic.pause(1000)
                                                                                                                                                                                                                                            evasionDirection *= -1
                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                            // Function to push enemy
                                                                                                                                                                                                                                            function pushEnemy() {
                                                                                                                                                                                                                                                robotbit.MotorRun(robotbit.Motors.M1A, 100)
                                                                                                                                                                                                                                                    robotbit.MotorRun(robotbit.Motors.M2A, 100)
                                                                                                                                                                                                                                                        basic.pause(500)
                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                        // Function to increase speed
                                                                                                                                                                                                                                                        function speedUp() {
                                                                                                                                                                                                                                                            speed += 25
                                                                                                                                                                                                                                                                if (speed > 100) {
                                                                                                                                                                                                                                                                        speed = 100
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                basic.showNumber(speed)
                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                // Function to play "vroom" sound
                                                                                                                                                                                                                                                                                function playVroomSound() {
                                                                                                                                                                                                                                                                                    music.playTone(Note.C, music.beat(BeatFraction.Whole))
                                                                                                                                                                                                                                                                                        basic.showIcon(IconNames.SmallDiamond)
                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                        // Function to evade enemy
                                                                                                                                                                                                                                                                                        function evadeEnemy(speed: number) {
                                                                                                                                                                                                                                                                                            robotbit.MotorRun(robotbit.Motors.M1A, speed * evasionDirection)
                                                                                                                                                                                                                                                                                                robotbit.MotorRun(robotbit.Motors.M2A, speed * evasionDirection)
                                                                                                                                                                                                                                                                                                    playEvadeSound()
                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                    // Function to celebrate when enemy is out
                                                                                                                                                                                                                                                                                                    function celebrateEnemyOut() {
                                                                                                                                                                                                                                                                                                        for (let i = 0; i < 2; i++) {
                                                                                                                                                                                                                                                                                                                robotbit.MotorRun(robotbit.Motors.M1A, 100)
                                                                                                                                                                                                                                                                                                                        robotbit.MotorRun(robotbit.Motors.M2A, -100)
                                                                                                                                                                                                                                                                                                                                basic.pause(1000)
                                                                                                                                                                                                                                                                                                                                        robotbit.MotorStopAll()
                                                                                                                                                                                                                                                                                                                                                basic.pause(500)
                                                                                                                                                                                                                                                                                                                                                        robotbit.MotorRun(robotbit.Motors.M1A, -100)
                                                                                                                                                                                                                                                                                                                                                                robotbit.MotorRun(robotbit.Motors.M2A, 100)
                                                                                                                                                                                                                                                                                                                                                                        basic.pause(1000)
                                                                                                                                                                                                                                                                                                                                                                                robotbit.MotorStopAll()
                                                                                                                                                                                                                                                                                                                                                                                        basic.pause(500)
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                            // Function to play evade sound
                                                                                                                                                                                                                                                                                                                                                                                            function playEvadeSound() {
                                                                                                                                                                                                                                                                                                                                                                                                music.playTone(262, music.beat(BeatFraction.Half))
                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                // Functions to display faces on the LED matrix
                                                                                                                                                                                                                                                                                                                                                                                                function displayAngryFace() {
                                                                                                                                                                                                                                                                                                                                                                                                    basic.showLeds(`
                                                                                                                                                                                                                                                                                                                                                                                                            . # . # .
                                                                                                                                                                                                                                                                                                                                                                                                                    # . . . #
                                                                                                                                                                                                                                                                                                                                                                                                                            . . . . .
                                                                                                                                                                                                                                                                                                                                                                                                                                    . # # # .
                                                                                                                                                                                                                                                                                                                                                                                                                                            # . # . #
                                                                                                                                                                                                                                                                                                                                                                                                                                                `)
                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                function displayHappyFace() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    basic.showLeds(`
                                                                                                                                                                                                                                                                                                                                                                                                                                                            . . . . .
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    . # . # .
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            . . . . .
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # . . . #
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            . # # # .
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                `)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function displaySadFace() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    basic.showLeds(`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            . . . . .
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    . # . # .
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            . . . . .
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # # # # #
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            . # . # .
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                `)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function displayHooray() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    basic.showString("Hooray")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Button handlers
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    input.onButtonPressed(Button.A, function () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        startRobot()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        input.onButtonPressed(Button.B, function () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            stopRobot()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Radio handlers
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            radio.onDataPacketReceived(function (receivedPacket) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let receivedString = receivedPacket.receivedString
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (receivedString == "start") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            startRobot()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else if (receivedString == "stop") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        stopRobot()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else if (receivedString == "speedUp") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    speedUp()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else if (receivedString == "vroom") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                playVroomSound()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    })

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Initial display
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    basic.showIcon(IconNames.Happy)